### PR TITLE
Add the requirement for Linux use in the README

### PR DESCRIPTION
**Pull request by QDelage**
MPlayer seems to be required, as for  this similar extension:
https://github.com/Itisfilipe/keyboard-sounds

### CODE REVIEW

**Review by mattogodoy — APPROVED** [review]
Nice!

**Comment by mattogodoy** [comment]
Done! Thanks for the PR :)

**Comment by QDelage** [comment]
You're welcome
I plan to use something like that in another extension, so I will draw from yours I guess

**Comment by mattogodoy** [comment]
Of course! Go ahead :)

**Pull request merged**
