### PR TITLE
Optimize performance and support volume adjustment

### PR DESCRIPTION
**Pull request by liangzr**
Thanks for your works, this extension is very interesting and does make sense to me. Usually, when we type the keyboard, we can hear the tapping as feedback, but there was no feedback from tapping once you using noise-canceling headphones,  it is really annoying to me.

I found some issues during using it, so I fix them and open this PR, could you please review and merge it:
- Optimize performance issue when repeating keystroke(keep key pressed)
- Support volume adjustment, working better with music(for `afplay` only now, [the whole list of players](https://github.com/shime/play-sound/blob/master/index.js))

### CODE REVIEW

**Comment by mattogodoy** [comment]
These are really good features!
I will test it in my local and update the extension in the Extensions Marketplace.

Thanks a lot!

**Comment by mattogodoy** [comment]
Okay, I have tested it in MacOS and Windows. I still have to test this in Linux.

Before releasing the new version I would like for the volume adjustment to also work in Linux. I don't know if there is a way for the `play-sound` library to set the volume for all players (not only for `afplayer`). Maybe we can do it by adding all of the players to the `playerAdapter`, but I don't know if it will work.
I've asked here: https://github.com/shime/play-sound/issues/35
We'll see if someone replies. 

As for Windows, I use `sWavPlayer` (https://www.dcmembers.com/skwire/download/swavplayer/) to play the sounds since there is no native player in that OS. The problem is that it has no volume options, so unless we find a different light-weight player, the volume will not be adjustable in Windows.

**Comment by mattogodoy** [comment]
Good news: I found a better player for windows that is smaller and also allows for volume control:
https://www.elifulkerson.com/projects/commandline-wav-player.php

I will integrate that and then run the necessary tests for linux. I'll keep you posted.

**Comment by liangzr** [comment]
Great job! This PR essentially introduce a way for volume control, and I only tested it in macOS(using `afplay`), other players from `play-sound` can be supported progressively. It seems that `play-sound` does not handle any arguments, just pass it through to the player. 

I also looked up the `mplayer`'s config about volume, but deleted the code before commit because it wasn't tested:

```ts
const playerAdapter = (opts: PlayerConfig) => ({
    mplayer: ['-af', `volume=${opts.vol}`],
    afplay: ['-v', opts.vol],
});
```

Hope this will help you. 
> Document of [https://www.mplayerhq.hu/DOCS/HTML/en/advaudio-volume.html)

**Pull request merged**
